import type {
  Trip,
  Roster,
  Itinerary,
  Reservations,
  Rooms,
  Flights,
  Todos,
  Expenses,
  Packlist,
  Emergency,
  Survey,
} from "./types";

export const seedTrip: Trip = {
  bride: "Jamie Schlacter",
  startDate: "2026-07-10",
  endDate: "2026-07-13",
  city: "Newport, RI",
  partySize: 9,
};

export const seedRoster: Roster = [
  {
    id: "jamie",
    name: "Jamie Schlacter",
    role: "bride",
    city: "NYC",
    phone: "224-545-9048",
    photoUrl: "/jamie/faces/jamie.jpg",
    colorToken: "coral",
  },
  {
    id: "hannah",
    name: "Hannah Schlacter",
    role: "moh",
    city: "Bay Area",
    phone: "847-404-8501",
    photoUrl: "/jamie/faces/hannah.jpg",
    colorToken: "tangerine",
  },
  {
    id: "ellie",
    name: "Ellie Schneider",
    role: "co-planner",
    city: "NYC",
    phone: "816-507-9355",
    photoUrl: "/jamie/faces/ellie.jpg",
    colorToken: "lime",
    dietary: ["No fish", "No pork"],
    drinkLevel: "Doesn't drink",
    emergencyContact: { name: "Alan Schneider", phone: "816-507-8678" },
    shirtSize: "M",
    pantsSize: "M (6-8)",
  },
  {
    id: "erica",
    name: "Erica Sadler",
    role: "guest",
    city: "NYC",
    phone: "240-893-6294",
    photoUrl: "/jamie/faces/erica.jpg",
    colorToken: "lavender",
    dietary: ["Gluten-free", "Pescatarian"],
    drinkLevel: "Moderate",
    emergencyContact: { name: "Scott Curran", phone: "917-984-0162" },
    shirtSize: "S",
    pantsSize: "S (2-4)",
  },
  {
    id: "mahip",
    name: "Mahip Grewal",
    role: "guest",
    city: "NYC",
    phone: "917-250-0413",
    photoUrl: "/jamie/faces/mahip.jpg",
    colorToken: "butter",
    dietary: ["Vegetarian (poultry/fish OK)"],
    drinkLevel: "Light",
    emergencyContact: { name: "Sanjay (dad)", phone: "917-667-7228" },
    shirtSize: "XS",
    pantsSize: "XS (00-0)",
  },
  {
    id: "gwenna",
    name: "Gwenna Heidkamp",
    role: "guest",
    city: "Chicago",
    phone: "847-274-6168",
    photoUrl: "/jamie/faces/gwenna.jpg",
    colorToken: "navySoft",
    dietary: [],
    drinkLevel: "Moderate",
    emergencyContact: { name: "Michael Kolimas", phone: "708-465-7820" },
    shirtSize: "M",
    pantsSize: "M (6-8)",
  },
  {
    id: "zoe",
    name: "Zoe Zirlin Bush",
    role: "guest",
    city: "Chicago",
    phone: "847-826-1916",
    photoUrl: "/jamie/faces/zoe.jpg",
    colorToken: "coral",
    dietary: ["Gluten-free"],
    drinkLevel: "Sober-ish (mostly NA)",
    emergencyContact: { name: "Max Bush", phone: "847-528-6299" },
    shirtSize: "M",
    pantsSize: "M (6-8)",
  },
  {
    id: "daniella",
    name: "Daniella Abramovich",
    role: "guest",
    city: "Vancouver",
    phone: "778-996-5510",
    photoUrl: "/jamie/faces/daniella.jpg",
    colorToken: "tangerine",
    dietary: ["No pork", "No shellfish"],
    drinkLevel: "Moderate",
    emergencyContact: { name: "Jill Diamond", phone: "604-838-5510" },
    shirtSize: "S",
    pantsSize: "S (2-4)",
  },
  {
    id: "abbey",
    name: "Abbey Stepnitz",
    role: "guest",
    city: "Chicago",
    phone: "734-660-3476",
    photoUrl: "/jamie/faces/abbey.jpg",
    colorToken: "lime",
    dietary: ["Pescatarian"],
    drinkLevel: "Light",
    emergencyContact: { name: "Mario Bravante", phone: "559-967-2614" },
    shirtSize: "M",
    pantsSize: "M (6-8)",
  },
];

export const seedItinerary: Itinerary = [
  {
    id: "fri-picnic",
    day: "fri",
    date: "2026-07-10",
    startTime: "12:00",
    title: "beach picnic",
    emoji: "🏖️",
    location: {
      name: "Easton's Beach (TBD)",
      address: "Memorial Blvd, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Easton%27s+Beach+Newport+RI",
    },
    dressCode: "swim + coverup",
    bring: ["towel", "sunscreen", "sunnies"],
    publicNote: "casual lunch on the beach to kick things off",
    status: "planned",
  },
  {
    id: "fri-pasta-beach",
    day: "fri",
    date: "2026-07-10",
    startTime: "19:00",
    title: "pasta beach",
    emoji: "🍝",
    location: {
      name: "Pasta Beach",
      address: "7 Memorial Blvd, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Pasta+Beach+Newport+RI",
    },
    dressCode: "dressy casual",
    publicNote: "dinner #1",
    status: "planned",
  },
  {
    id: "sat-wallys",
    day: "sat",
    date: "2026-07-11",
    startTime: "11:00",
    title: "wally's wieners",
    emoji: "🌭",
    location: {
      name: "Wally's Wieners",
      address: "374 Thames St, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Wally%27s+Wieners+Newport+RI",
    },
    dressCode: "bach merch?",
    publicNote: "brunch + the famous espresso martini towers",
    status: "planned",
  },
  {
    id: "sat-cruise",
    day: "sat",
    date: "2026-07-11",
    startTime: "19:30",
    endTime: "20:30",
    title: "gansett sunset cruise",
    emoji: "🛥️",
    location: {
      name: "Gansett Cruises",
      address: "2 Bowen's Landing, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=2+Bowen%27s+Landing+Newport+RI",
    },
    dressCode: "SOFT-SOLED SHOES ONLY — no heels!",
    bring: ["light jacket", "sunset selfie energy"],
    publicNote:
      "check in 7:15pm sharp, boat leaves promptly. drinks served onboard.",
    reservationId: "res-cruise",
    status: "confirmed",
  },
  {
    id: "sat-mooring",
    day: "sat",
    date: "2026-07-11",
    startTime: "21:00",
    title: "the mooring",
    emoji: "🦞",
    location: {
      name: "The Mooring Seafood Kitchen & Bar",
      address: "1 Sayer's Wharf, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=The+Mooring+Newport+RI",
    },
    dressCode: "semi-formal",
    publicNote: "the big dinner",
    status: "planned",
  },
];

export const seedReservations: Reservations = [
  {
    id: "res-burbank",
    name: "Burbank Rose Inn",
    emoji: "🏠",
    when: "Fri 7/10 – Mon 7/13",
    partySize: 9,
    owner: "hannah",
    status: "paid",
    totalCost: 3955,
    contact: {
      phone: "(401) 688-7958",
      email: "Burbankrose@yahoo.com",
      url: "https://burbankrose.com",
    },
    internalNote:
      "Hannah paid full deposit Jan 2026 on Sam's Chase. Cancellable for full refund up to ~2 weeks out.",
    guestNote: "where we're staying",
  },
  {
    id: "res-cruise",
    itineraryId: "sat-cruise",
    name: "Gansett Sunset Cruise",
    emoji: "🛥️",
    when: "Sat 7/11 · 7:30pm",
    partySize: 10,
    owner: "hannah",
    status: "paid",
    confirmationNumber: "GTC-1467998",
    totalCost: 520,
    contact: { phone: "(401) 619-1300", url: "https://gansettcruises.com" },
    internalNote:
      "Booking ref 1367202161. 24h cancel policy, no refunds for missing boat.",
    guestNote: "saturday evening boat ride at sunset",
  },
  {
    id: "res-pasta-beach",
    itineraryId: "fri-pasta-beach",
    name: "Pasta Beach",
    emoji: "🍝",
    when: "Fri 7/10 · 7pm",
    partySize: 9,
    owner: "ellie",
    status: "pending",
    contact: { url: "https://resy.com/cities/newport-ri/venues/pasta-beach" },
  },
  {
    id: "res-mooring",
    itineraryId: "sat-mooring",
    name: "The Mooring",
    emoji: "🦞",
    when: "Sat 7/11 · 9pm",
    partySize: 9,
    owner: "ellie",
    status: "pending",
    contact: { url: "https://mooringrestaurant.com" },
  },
  {
    id: "res-wallys",
    itineraryId: "sat-wallys",
    name: "Wally's Wieners",
    emoji: "🌭",
    when: "Sat 7/11 · 11am",
    partySize: 9,
    owner: "ellie",
    status: "pending",
    contact: { url: "https://wallyswieners.com" },
  },
  {
    id: "res-picnic",
    itineraryId: "fri-picnic",
    name: "Beach picnic",
    emoji: "🏖️",
    when: "Fri 7/10 · noon",
    partySize: 9,
    owner: "hannah",
    status: "tbd",
    internalNote: "Need to confirm beach + grab catering or DIY",
  },
];

export const seedRooms: Rooms = {
  layout: {
    floor1: { full: 1, queenPullout: 2 },
    floor2: { king: 1, bunkTop: 1, bunkBottom: 1 },
    floor3: { queen: 1, queenPullout: 2 },
  },
  assignments: [
    { floor: 1, bed: "full", attendeeId: null },
    { floor: 1, bed: "queenPullout-1", attendeeId: null },
    { floor: 1, bed: "queenPullout-2", attendeeId: null },
    { floor: 2, bed: "king", attendeeId: null },
    { floor: 2, bed: "bunkTop", attendeeId: null },
    { floor: 2, bed: "bunkBottom", attendeeId: null },
    { floor: 3, bed: "queen", attendeeId: null },
    { floor: 3, bed: "queenPullout-1", attendeeId: null },
    { floor: 3, bed: "queenPullout-2", attendeeId: null },
  ],
};

export const seedFlights: Flights = {
  jamie: { attendeeId: "jamie", status: "tbd" },
  hannah: { attendeeId: "hannah", status: "tbd" },
  ellie: { attendeeId: "ellie", status: "tbd" },
  erica: { attendeeId: "erica", status: "tbd" },
  mahip: { attendeeId: "mahip", status: "tbd" },
  gwenna: { attendeeId: "gwenna", status: "tbd" },
  zoe: { attendeeId: "zoe", status: "tbd" },
  daniella: { attendeeId: "daniella", status: "tbd" },
  abbey: { attendeeId: "abbey", status: "tbd" },
};

export const seedTodos: Todos = [
  {
    id: "todo-1",
    title: "Confirm Pasta Beach reservation",
    owner: "ellie",
    dueDate: "2026-05-15",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-2",
    title: "Confirm The Mooring reservation",
    owner: "ellie",
    dueDate: "2026-05-15",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-3",
    title: "Confirm Wally's brunch reservation",
    owner: "ellie",
    dueDate: "2026-05-15",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-4",
    title: "Create Splitwise group + add members",
    owner: "hannah",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-5",
    title: "Order matching merch (sizes from survey)",
    owner: "hannah",
    dueDate: "2026-06-15",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-6",
    title: "Plan beach picnic logistics (catering vs DIY)",
    owner: "hannah",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-7",
    title: "Decide rental car pickups + group rides from PVD/BOS",
    owner: "shared",
    done: false,
    createdAt: new Date().toISOString(),
  },
];

export const seedExpenses: Expenses = {
  splitwiseUrl: "",
  splitwiseJoined: {
    jamie: false,
    hannah: false,
    ellie: false,
    erica: false,
    mahip: false,
    gwenna: false,
    zoe: false,
    daniella: false,
    abbey: false,
  },
  prePaid: [
    {
      label: "Burbank Rose Inn (3 nights)",
      amount: 3955,
      paidBy: "hannah",
      loggedToSplitwise: false,
    },
    {
      label: "Gansett Sunset Cruise",
      amount: 520,
      paidBy: "hannah",
      loggedToSplitwise: false,
    },
  ],
  estimatedPerPerson: 716.71,
};

export const seedPacklist: Packlist = [
  {
    name: "beach day",
    emoji: "🏖️",
    items: [
      { id: "p1", label: "swimsuit (or 2)" },
      { id: "p2", label: "coverup" },
      { id: "p3", label: "beach towel" },
      { id: "p4", label: "sunscreen" },
      { id: "p5", label: "sunnies" },
    ],
  },
  {
    name: "dinners",
    emoji: "🍝",
    items: [
      { id: "p6", label: "fri night fit (dressy casual)" },
      { id: "p7", label: "sat night fit (semi-formal)" },
      { id: "p8", label: "comfy shoes for the cruise — NO heels" },
    ],
  },
  {
    name: "daytime",
    emoji: "☀️",
    items: [
      { id: "p9", label: "casual outfits for brunch + walking" },
      { id: "p10", label: "sneakers / flats" },
      { id: "p11", label: "bach merch (we'll have it!)" },
    ],
  },
  {
    name: "essentials",
    emoji: "✨",
    items: [
      { id: "p12", label: "phone charger" },
      { id: "p13", label: "ID + cards" },
      { id: "p14", label: "any meds you need" },
      { id: "p15", label: "venmo + splitwise installed" },
    ],
  },
];

export const seedEmergency: Emergency = {
  houseAddress: "111 Memorial Blvd W, Newport, RI 02840",
  houseStaffPhone: "(401) 688-7958",
  nearestHospital: {
    name: "Newport Hospital",
    address: "11 Friendship St, Newport, RI 02840",
    phone: "(401) 846-6400",
  },
  planners: [
    { name: "Hannah Schlacter (MOH)", phone: "847-404-8501" },
    { name: "Ellie Schneider (co-planner)", phone: "816-507-9355" },
  ],
};

export const seedSurvey: Survey = [
  {
    attendeeId: "zoe",
    timestamp: "2026-03-28T16:50:02",
    shirtSize: "M",
    sweatshirtSize: "M",
    pantsSize: "M (6-8)",
    foodAllergies: "None",
    dietary: "Gluten-free",
    otherMedical: "None",
    beenToNewport: "No",
    skipOrCantDo: "Nothing",
    drinkLevel: "Sober-ish — mostly NA, occasional sip",
    roommatePref: "No preference",
    emergencyContact: "Max Bush — 847-528-6299",
  },
  {
    attendeeId: "daniella",
    timestamp: "2026-03-29T15:16:59",
    shirtSize: "S",
    sweatshirtSize: "S",
    pantsSize: "S (2-4)",
    foodAllergies: "None",
    dietary: "No pork or shellfish",
    otherMedical: "Allergic to Acetaminophen",
    beenToNewport: "No",
    skipOrCantDo: "Nothing",
    drinkLevel: "Moderate",
    roommatePref: "No preference",
    emergencyContact: "Jill Diamond — 604-838-5510",
  },
  {
    attendeeId: "gwenna",
    timestamp: "2026-03-29T15:32:30",
    shirtSize: "M",
    sweatshirtSize: "M",
    pantsSize: "M (6-8)",
    foodAllergies: "None",
    dietary: "None — eats everything",
    otherMedical: "None",
    beenToNewport: "No",
    skipOrCantDo: "Nothing",
    drinkLevel: "Moderate",
    roommatePref: "No preference",
    emergencyContact: "Michael Kolimas — 708-465-7820",
    notes: "Happy to plan some fun bach games!",
  },
  {
    attendeeId: "abbey",
    timestamp: "2026-03-30T07:24:19",
    shirtSize: "M",
    sweatshirtSize: "M",
    pantsSize: "M (6-8)",
    foodAllergies: "None",
    dietary: "Pescatarian — veggie + seafood",
    otherMedical: "Mild motion sickness — front/middle seat helps",
    beenToNewport: "No",
    skipOrCantDo: "Nothing",
    drinkLevel: "Light",
    roommatePref: "No preference",
    emergencyContact: "Mario Bravante — 559-967-2614",
    notes: "So excited to celebrate Jamie!",
  },
  {
    attendeeId: "ellie",
    timestamp: "2026-03-30T22:09:18",
    shirtSize: "M",
    sweatshirtSize: "M",
    pantsSize: "M (6-8)",
    foodAllergies: "None",
    dietary: "No fish or pork",
    otherMedical: "None",
    beenToNewport: "Yes",
    skipOrCantDo: "Nothing",
    drinkLevel: "Doesn't drink",
    roommatePref: "—",
    emergencyContact: "Alan Schneider — 816-507-8678",
  },
  {
    attendeeId: "erica",
    timestamp: "2026-04-01T11:54:39",
    shirtSize: "S",
    sweatshirtSize: "S",
    pantsSize: "S (2-4)",
    foodAllergies: "Gluten",
    dietary: "Gluten-free, pescatarian",
    otherMedical: "Knee injury — avoid intense physical activity",
    beenToNewport: "No",
    skipOrCantDo: "Avoid intense physical activity",
    drinkLevel: "Moderate",
    roommatePref: "Mahip",
    emergencyContact: "Scott Curran — 917-984-0162",
  },
  {
    attendeeId: "mahip",
    timestamp: "2026-04-09T19:48:17",
    shirtSize: "XS",
    sweatshirtSize: "S",
    pantsSize: "XS (00-0)",
    foodAllergies: "None",
    dietary: "Vegetarian — no red meat, eats poultry/fish",
    otherMedical: "None",
    beenToNewport: "No",
    skipOrCantDo: "—",
    drinkLevel: "Light",
    roommatePref: "Erica Sadler",
    emergencyContact: "Sanjay (dad) — 917-667-7228",
  },
];
