import type {
  Trip,
  Roster,
  Itinerary,
  Reservations,
  Rooms,
  Flights,
  Todos,
  Expenses,
  Packlist,
  Emergency,
  Survey,
} from "./types";

export const seedTrip: Trip = {
  bride: "Jamie Schlacter",
  startDate: "2026-07-10",
  endDate: "2026-07-12",
  city: "Newport, RI",
  partySize: 9,
};

export const seedRoster: Roster = [
  {
    id: "jamie",
    name: "Jamie Schlacter",
    role: "bride",
    city: "NYC",
    phone: "224-545-9048",
    photoUrl: "/jamie/faces/jamie.jpg",
    colorToken: "coral",
  },
  {
    id: "hannah",
    name: "Hannah Schlacter",
    role: "moh",
    city: "Bay Area",
    phone: "847-404-8501",
    photoUrl: "/jamie/faces/hannah.jpg",
    colorToken: "tangerine",
  },
  {
    id: "ellie",
    name: "Ellie Schneider",
    role: "co-planner",
    city: "NYC",
    phone: "816-507-9355",
    photoUrl: "/jamie/faces/ellie.jpg",
    colorToken: "lime",
    dietary: ["No fish", "No pork"],
    drinkLevel: "Doesn't drink",
    emergencyContact: { name: "Alan Schneider", phone: "816-507-8678" },
    shirtSize: "M",
    pantsSize: "M (6-8)",
  },
  {
    id: "erica",
    name: "Erica Sadler",
    role: "guest",
    city: "NYC",
    phone: "240-893-6294",
    photoUrl: "/jamie/faces/erica.jpg",
    colorToken: "lavender",
    dietary: ["Gluten-free", "Pescatarian"],
    drinkLevel: "Moderate",
    emergencyContact: { name: "Scott Curran", phone: "917-984-0162" },
    shirtSize: "S",
    pantsSize: "S (2-4)",
  },
  {
    id: "mahip",
    name: "Mahip Grewal",
    role: "guest",
    city: "NYC",
    phone: "917-250-0413",
    photoUrl: "/jamie/faces/mahip-v2.jpg",
    colorToken: "butter",
    dietary: ["Vegetarian (poultry/fish OK)"],
    drinkLevel: "Light",
    emergencyContact: { name: "Sanjay (dad)", phone: "917-667-7228" },
    shirtSize: "XS",
    pantsSize: "XS (00-0)",
  },
  {
    id: "gwenna",
    name: "Gwenna Heidkamp",
    role: "guest",
    city: "Chicago",
    phone: "847-274-6168",
    photoUrl: "/jamie/faces/gwenna.jpg",
    colorToken: "navySoft",
    dietary: [],
    drinkLevel: "Moderate",
    emergencyContact: { name: "Michael Kolimas", phone: "708-465-7820" },
    shirtSize: "M",
    pantsSize: "M (6-8)",
  },
  {
    id: "zoe",
    name: "Zoe Zirlin Bush",
    role: "guest",
    city: "Chicago",
    phone: "847-826-1916",
    photoUrl: "/jamie/faces/zoe.jpg",
    colorToken: "coral",
    dietary: ["Gluten-free"],
    drinkLevel: "Sober-ish (mostly NA)",
    emergencyContact: { name: "Max Bush", phone: "847-528-6299" },
    shirtSize: "M",
    pantsSize: "M (6-8)",
  },
  {
    id: "daniella",
    name: "Daniella Abramovich",
    role: "guest",
    city: "Vancouver",
    phone: "778-996-5510",
    photoUrl: "/jamie/faces/daniella.jpg",
    colorToken: "tangerine",
    dietary: ["No pork", "No shellfish"],
    drinkLevel: "Moderate",
    emergencyContact: { name: "Jill Diamond", phone: "604-838-5510" },
    shirtSize: "S",
    pantsSize: "S (2-4)",
  },
  {
    id: "abbey",
    name: "Abbey Stepnitz",
    role: "guest",
    city: "Chicago",
    phone: "734-660-3476",
    photoUrl: "/jamie/faces/abbey.jpg",
    colorToken: "lime",
    dietary: ["Pescatarian"],
    drinkLevel: "Light",
    emergencyContact: { name: "Mario Bravante", phone: "559-967-2614" },
    shirtSize: "M",
    pantsSize: "M (6-8)",
  },
];

export const seedItinerary: Itinerary = [
  // ── Friday ─────────────────────────────────────────────────────────────────
  {
    id: "fri-lunch",
    day: "fri",
    date: "2026-07-10",
    startTime: "12:00",
    title: "lunch downtown",
    emoji: "🍴",
    location: {
      name: "The Red Parrot (TBD)",
      address: "348 Thames St, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=The+Red+Parrot+Newport+RI",
    },
    dressCode: "casual",
    publicNote: "first meal in town — restaurant TBD.",
    status: "planned",
  },
  {
    id: "fri-cliff-walk",
    day: "fri",
    date: "2026-07-10",
    startTime: "13:30",
    title: "cliff walk + downtown",
    emoji: "🌊",
    location: {
      name: "Cliff Walk",
      address: "Memorial Blvd, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Cliff+Walk+Newport+RI",
    },
    dressCode: "walking shoes",
    publicNote: "an afternoon stroll along the cliffs and into town.",
    status: "planned",
  },
  {
    id: "fri-pasta-beach",
    day: "fri",
    date: "2026-07-10",
    startTime: "18:00",
    title: "pasta beach",
    emoji: "🍝",
    location: {
      name: "Pasta Beach",
      address: "7 Memorial Blvd, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Pasta+Beach+Newport+RI",
    },
    dressCode:
      "Something Blue — Jamie wears white, everyone else wears a different shade of blue.",
    publicNote: "dinner #1 — leaving the inn by 5:50.",
    status: "planned",
  },
  {
    id: "fri-games",
    day: "fri",
    date: "2026-07-10",
    startTime: "20:00",
    title: "games, candy salad & Mamma Mia sing-along",
    emoji: "🎬",
    location: {
      name: "Burbank Rose Inn",
      address: "111 Memorial Blvd W, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=111+Memorial+Blvd+W+Newport+RI",
    },
    publicNote:
      "A fun night in all about Jamie — games, the famous candy salad, and a Mamma Mia movie sing-along. Bring your singing voice!",
    status: "planned",
  },

  // ── Saturday ───────────────────────────────────────────────────────────────
  {
    id: "sat-codough",
    day: "sat",
    date: "2026-07-11",
    startTime: "08:30",
    title: "co-dough bakery",
    emoji: "🥐",
    location: {
      name: "Co-Dough Bakery",
      address: "Newport, RI",
      mapsUrl: "https://maps.google.com/?q=Co-Dough+Bakery+Newport+RI",
    },
    publicNote:
      "fresh hot buns + donuts every Saturday at 8:30am. quick early stop before coffee.",
    status: "planned",
  },
  {
    id: "sat-coffee",
    day: "sat",
    date: "2026-07-11",
    startTime: "09:00",
    title: "coffee",
    emoji: "☕",
    location: {
      name: "Nitro Bar",
      address: "60 Bellevue Ave, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Nitro+Bar+Newport+RI",
    },
    publicNote: "soft start before pilates.",
    status: "planned",
  },
  {
    id: "sat-pilates",
    day: "sat",
    date: "2026-07-11",
    startTime: "10:00",
    title: "reformer pilates",
    emoji: "🧘",
    location: {
      name: "Thrive Newport",
      address: "70 Memorial Blvd, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Thrive+Newport+RI",
    },
    dressCode: "workout fit",
    bring: ["grippy socks (available to buy at the studio)"],
    publicNote: "reformer class — bring grippy socks (available to buy there) and we'll each sign a waiver.",
    status: "planned",
  },
  {
    id: "sat-wallys",
    day: "sat",
    date: "2026-07-11",
    startTime: "12:00",
    title: "wally's wieners",
    emoji: "🌭",
    location: {
      name: "Wally's Wieners",
      address: "374 Thames St, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Wally%27s+Wieners+Newport+RI",
    },
    dressCode: "bach merch?",
    publicNote: "casual lunch — hot dogs on Thames Street. after pilates we'll head back to the inn to change for the beach first.",
    status: "planned",
  },
  {
    id: "sat-beach",
    day: "sat",
    date: "2026-07-11",
    startTime: "13:00",
    endTime: "17:00",
    title: "beach day",
    emoji: "🏖️",
    location: {
      name: "Easton's Beach",
      address: "175 Memorial Blvd, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Easton%27s+Beach+Newport+RI",
    },
    dressCode: "swim + coverup",
    bring: ["towel", "sunscreen", "sunnies", "del's lemonade money"],
    publicNote: "del's lemonade and the ocean. wander into town if you want.",
    status: "planned",
  },
  {
    id: "sat-cruise",
    day: "sat",
    date: "2026-07-11",
    startTime: "19:30",
    endTime: "20:30",
    title: "gansett sunset cruise",
    emoji: "🛥️",
    location: {
      name: "Gansett Cruises",
      address: "2 Bowen's Landing, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=2+Bowen%27s+Landing+Newport+RI",
    },
    dressCode:
      "The Last Disco — Jamie wears white, everyone else dresses sparkly + glittery.",
    bring: ["light jacket", "sunset selfie energy"],
    publicNote:
      "be at the boat 20 minutes early — check-in is 7:10pm, the boat leaves at 7:30pm on time. leave the inn by 7:00pm. drinks served onboard.",
    reservationId: "res-cruise",
    status: "confirmed",
  },
  {
    id: "sat-oyster",
    day: "sat",
    date: "2026-07-11",
    startTime: "20:30",
    title: "midtown oyster bar",
    emoji: "🦞",
    location: {
      name: "Midtown Oyster Bar",
      address: "345 Thames St, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=Midtown+Oyster+Bar+Newport+RI",
    },
    dressCode:
      "The Last Disco — Jamie wears white, everyone else dresses sparkly + glittery. Semi-formal.",
    publicNote: "dinner with the full group at Midtown Oyster Bar.",
    status: "planned",
  },
  {
    id: "sat-out",
    day: "sat",
    date: "2026-07-11",
    startTime: "22:00",
    title: "going out",
    emoji: "🥂",
    location: {
      name: "The Landing · Dockside · Smugglers · O'Briens",
      address: "Thames St, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=The+Landing+Newport+RI",
    },
    dressCode: "The Last Disco — keep it sparkly + glittery.",
    publicNote:
      "bar crawl through the wharf. Recommended: The Landing, Dockside, Smugglers Waterfront Bar, O'Briens Pub.",
    status: "planned",
  },

  // ── Sunday ─────────────────────────────────────────────────────────────────
  {
    id: "sun-brunch",
    day: "sun",
    date: "2026-07-12",
    startTime: "11:00",
    title: "brunch at cru",
    emoji: "🍳",
    location: {
      name: "CRU Cafe",
      address: "194 Bellevue Ave, Newport, RI 02840",
      mapsUrl: "https://maps.google.com/?q=CRU+Cafe+Newport+RI",
    },
    publicNote: "casual, order-at-counter brunch spot",
    status: "planned",
  },
];

export const seedReservations: Reservations = [
  {
    id: "res-burbank",
    name: "Burbank Rose Inn",
    emoji: "🏠",
    when: "Fri 7/10 – Mon 7/13",
    partySize: 9,
    owner: "hannah",
    status: "paid",
    totalCost: 3955,
    contact: {
      phone: "(401) 688-7958",
      email: "Burbankrose@yahoo.com",
      url: "https://burbankrose.com",
    },
    internalNote:
      "Hannah paid full deposit Jan 2026 on Sam's Chase. Cancellable for full refund up to ~2 weeks out.",
    guestNote: "where we're staying",
  },
  {
    id: "res-cruise",
    itineraryId: "sat-cruise",
    name: "Gansett Sunset Cruise",
    emoji: "🛥️",
    when: "Sat 7/11 · 7:30pm",
    partySize: 10,
    owner: "hannah",
    status: "paid",
    confirmationNumber: "GTC-1467998",
    totalCost: 520,
    contact: { phone: "(401) 619-1300", url: "https://gansettcruises.com" },
    internalNote:
      "Booking ref 1367202161. 24h cancel policy, no refunds for missing boat.",
    guestNote: "saturday evening boat ride at sunset",
  },
  {
    id: "res-pasta-beach",
    itineraryId: "fri-pasta-beach",
    name: "Pasta Beach",
    emoji: "🍝",
    when: "Fri 7/10 · 7pm",
    partySize: 9,
    owner: "ellie",
    status: "pending",
    contact: { url: "https://resy.com/cities/newport-ri/venues/pasta-beach" },
  },
  {
    id: "res-mooring",
    itineraryId: "sat-mooring",
    name: "The Mooring",
    emoji: "🦞",
    when: "Sat 7/11 · 9pm",
    partySize: 9,
    owner: "ellie",
    status: "pending",
    contact: { url: "https://mooringrestaurant.com" },
  },
  {
    id: "res-wallys",
    itineraryId: "sat-wallys",
    name: "Wally's Wieners",
    emoji: "🌭",
    when: "Sat 7/11 · 11am",
    partySize: 9,
    owner: "ellie",
    status: "pending",
    contact: { url: "https://wallyswieners.com" },
  },
  {
    id: "res-picnic",
    itineraryId: "fri-picnic",
    name: "Beach picnic",
    emoji: "🏖️",
    when: "Fri 7/10 · noon",
    partySize: 9,
    owner: "hannah",
    status: "tbd",
    internalNote: "Need to confirm beach + grab catering or DIY",
  },
];

export const seedRooms: Rooms = {
  layout: {
    floor1: { full: 1, queenPullout: 2 },
    floor2: { king: 1, bunkTop: 1, bunkBottom: 1 },
    floor3: { queen: 1, queenPullout: 2 },
  },
  assignments: [
    { floor: 1, bed: "full", attendeeId: null },
    { floor: 1, bed: "queenPullout-1", attendeeId: null },
    { floor: 1, bed: "queenPullout-2", attendeeId: null },
    { floor: 2, bed: "king", attendeeId: null },
    { floor: 2, bed: "bunkTop", attendeeId: null },
    { floor: 2, bed: "bunkBottom", attendeeId: null },
    { floor: 3, bed: "queen", attendeeId: null },
    { floor: 3, bed: "queenPullout-1", attendeeId: null },
    { floor: 3, bed: "queenPullout-2", attendeeId: null },
  ],
};

export const seedFlights: Flights = {
  // 7 of us share a booked rental car from NYC; Zoe + Daniella fly into Providence.
  jamie: { attendeeId: "jamie", status: "tbd", mode: "car" },
  hannah: { attendeeId: "hannah", status: "tbd", mode: "car" },
  ellie: { attendeeId: "ellie", status: "tbd", mode: "car" },
  erica: { attendeeId: "erica", status: "tbd", mode: "car" },
  mahip: { attendeeId: "mahip", status: "tbd", mode: "car" },
  gwenna: { attendeeId: "gwenna", status: "tbd", mode: "car" },
  abbey: { attendeeId: "abbey", status: "tbd", mode: "car" },
  zoe: { attendeeId: "zoe", status: "tbd", mode: "fly", arrivalAirport: "PVD" },
  daniella: {
    attendeeId: "daniella",
    status: "tbd",
    mode: "fly",
    arrivalAirport: "PVD",
  },
};

export const seedTodos: Todos = [
  {
    id: "todo-1",
    title: "Confirm Pasta Beach reservation",
    owner: "ellie",
    dueDate: "2026-05-15",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-2",
    title: "Confirm The Mooring reservation",
    owner: "ellie",
    dueDate: "2026-05-15",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-3",
    title: "Confirm Wally's brunch reservation",
    owner: "ellie",
    dueDate: "2026-05-15",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-4",
    title: "Create Splitwise group + add members",
    owner: "hannah",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-5",
    title: "Order matching merch (sizes from survey)",
    owner: "hannah",
    dueDate: "2026-06-15",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-6",
    title: "Plan beach picnic logistics (catering vs DIY)",
    owner: "hannah",
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo-7",
    title: "Decide rental car pickups + group rides from PVD/BOS",
    owner: "shared",
    done: false,
    createdAt: new Date().toISOString(),
  },
];

export const seedExpenses: Expenses = {
  splitwiseUrl: "https://www.splitwise.com/join/hSzXcWPtUfb+ecikr?v=e",
  splitwiseJoined: {
    jamie: false,
    hannah: false,
    ellie: false,
    erica: false,
    mahip: false,
    gwenna: false,
    zoe: false,
    daniella: false,
    abbey: false,
  },
  prePaid: [
    {
      label: "Burbank Rose Inn (3 nights)",
      amount: 3955,
      paidBy: "hannah",
      loggedToSplitwise: false,
    },
    {
      label: "Gansett Sunset Cruise",
      amount: 520,
      paidBy: "hannah",
      loggedToSplitwise: false,
    },
  ],
  estimatedPerPerson: 716.71,
};

export const seedPacklist: Packlist = [
  {
    name: "for the bach",
    emoji: "🎀",
    items: [
      { id: "p3", label: "beach towel — the inn doesn't supply them" },
      { id: "p18", label: "pilates grippy socks (borrow, or buy at the studio if needed)" },
      { id: "p16", label: "candy for the candy salad (any kind — bring a bag)" },
    ],
  },
  {
    name: "outfits by the itinerary",
    emoji: "👗",
    items: [
      { id: "p6", label: "fri night — Something Blue (a shade of blue; Jamie wears white)" },
      { id: "p22", label: "sat morning — workout outfit for pilates" },
      { id: "p19", label: "sat day — swimsuit + coverup for the beach" },
      { id: "p7", label: "sat night — The Last Disco (colorful and/or sparkly; Jamie wears white)" },
      { id: "p8", label: "dressier shoes (not just comfy ones) for the cruise + Saturday dinner / night out" },
      { id: "p17", label: "a sweater or jacket for cool evenings out" },
    ],
  },
  {
    name: "daytime",
    emoji: "☀️",
    items: [
      { id: "p9", label: "casual outfits for brunch + walking" },
      { id: "p10", label: "sneakers / flats" },
      { id: "p5", label: "sunnies" },
    ],
  },
  {
    name: "essentials",
    emoji: "✨",
    items: [
      { id: "p12", label: "phone charger" },
      { id: "p13", label: "ID + cards" },
      { id: "p14", label: "any meds you need" },
      { id: "p20", label: "sunblock" },
      { id: "p21", label: "toiletries" },
    ],
  },
];

export const seedEmergency: Emergency = {
  houseAddress: "111 Memorial Blvd W, Newport, RI 02840",
  houseStaffPhone: "(401) 688-7958",
  nearestHospital: {
    name: "Newport Hospital",
    address: "11 Friendship St, Newport, RI 02840",
    phone: "(401) 846-6400",
  },
  planners: [
    { name: "Hannah Schlacter (MOH)", phone: "847-404-8501" },
    { name: "Ellie Schneider (co-planner)", phone: "816-507-9355" },
  ],
};

export const seedSurvey: Survey = [
  {
    attendeeId: "zoe",
    timestamp: "2026-03-28T16:50:02",
    shirtSize: "M",
    sweatshirtSize: "M",
    pantsSize: "M (6-8)",
    foodAllergies: "None",
    dietary: "Gluten-free",
    otherMedical: "None",
    beenToNewport: "No",
    skipOrCantDo: "Nothing",
    drinkLevel: "Sober-ish — mostly NA, occasional sip",
    roommatePref: "No preference",
    emergencyContact: "Max Bush — 847-528-6299",
  },
  {
    attendeeId: "daniella",
    timestamp: "2026-03-29T15:16:59",
    shirtSize: "S",
    sweatshirtSize: "S",
    pantsSize: "S (2-4)",
    foodAllergies: "None",
    dietary: "No pork or shellfish",
    otherMedical: "Allergic to Acetaminophen",
    beenToNewport: "No",
    skipOrCantDo: "Nothing",
    drinkLevel: "Moderate",
    roommatePref: "No preference",
    emergencyContact: "Jill Diamond — 604-838-5510",
  },
  {
    attendeeId: "gwenna",
    timestamp: "2026-03-29T15:32:30",
    shirtSize: "M",
    sweatshirtSize: "M",
    pantsSize: "M (6-8)",
    foodAllergies: "None",
    dietary: "None — eats everything",
    otherMedical: "None",
    beenToNewport: "No",
    skipOrCantDo: "Nothing",
    drinkLevel: "Moderate",
    roommatePref: "No preference",
    emergencyContact: "Michael Kolimas — 708-465-7820",
    notes: "Happy to plan some fun bach games!",
  },
  {
    attendeeId: "abbey",
    timestamp: "2026-03-30T07:24:19",
    shirtSize: "M",
    sweatshirtSize: "M",
    pantsSize: "M (6-8)",
    foodAllergies: "None",
    dietary: "Pescatarian — veggie + seafood",
    otherMedical: "Mild motion sickness — front/middle seat helps",
    beenToNewport: "No",
    skipOrCantDo: "Nothing",
    drinkLevel: "Light",
    roommatePref: "No preference",
    emergencyContact: "Mario Bravante — 559-967-2614",
    notes: "So excited to celebrate Jamie!",
  },
  {
    attendeeId: "ellie",
    timestamp: "2026-03-30T22:09:18",
    shirtSize: "M",
    sweatshirtSize: "M",
    pantsSize: "M (6-8)",
    foodAllergies: "None",
    dietary: "No fish or pork",
    otherMedical: "None",
    beenToNewport: "Yes",
    skipOrCantDo: "Nothing",
    drinkLevel: "Doesn't drink",
    roommatePref: "—",
    emergencyContact: "Alan Schneider — 816-507-8678",
  },
  {
    attendeeId: "erica",
    timestamp: "2026-04-01T11:54:39",
    shirtSize: "S",
    sweatshirtSize: "S",
    pantsSize: "S (2-4)",
    foodAllergies: "Gluten",
    dietary: "Gluten-free, pescatarian",
    otherMedical: "Knee injury — avoid intense physical activity",
    beenToNewport: "No",
    skipOrCantDo: "Avoid intense physical activity",
    drinkLevel: "Moderate",
    roommatePref: "Mahip",
    emergencyContact: "Scott Curran — 917-984-0162",
  },
  {
    attendeeId: "mahip",
    timestamp: "2026-04-09T19:48:17",
    shirtSize: "XS",
    sweatshirtSize: "S",
    pantsSize: "XS (00-0)",
    foodAllergies: "None",
    dietary: "Vegetarian — no red meat, eats poultry/fish",
    otherMedical: "None",
    beenToNewport: "No",
    skipOrCantDo: "—",
    drinkLevel: "Light",
    roommatePref: "Erica Sadler",
    emergencyContact: "Sanjay (dad) — 917-667-7228",
  },
];
