export type ServiceLayer = {
  layer: string;
  note: string;
  items: string[];
};

export type Project = {
  slug: string;
  title: string;
  oneLiner: string;
  tileInsight: string;
  tags: string[];
  thumbnailColor: string;
  thumbnailImage?: string;
  problem: string;
  hypothesis: string;
  built: string;
  broke: string;
  learned: string;
  nextSteps: string;
  keyLearning: string;
  services?: ServiceLayer[];
  artifacts: {
    screenshots: string[];
    screenshotCaptions?: string[];
    liveUrl?: string;
    videoUrl?: string;
  };
};

export const projects: Project[] = [
  {
    slug: "muse",
    title: "Muse Shopping",
    oneLiner: "A personalized shopping feed across 200+ brands — follow them like Instagram, built solo without a CS degree.",
    tileInsight: "Getting something built and trusting what was built are not the same problem.",
    tags: ["Consumer", "AI", "Full-Stack"],
    thumbnailColor: "#EDD5C0",
    thumbnailImage: "/projects/muse/logo-gradient.svg",
    problem: "I shop across ten different sites simultaneously — each one starting fresh with no memory of what I liked. The discovery layer of fashion is broken: you're either drowning in generic suggestions or running your own research operation across tabs. I wanted one place that worked like a social feed and actually learned your taste.",
    hypothesis: "The cold start problem in personalization is usually solved with a quiz. I wanted to test whether you could skip that — let behavioral signals do the work instead. If every click, save, and add-to-cart reveals taste, you should be able to build a real style profile without asking a single question.",
    built: "Follow brands the way you follow people on Instagram; their new products surface in a single feed. A Gmail integration pre-populates your brand follows from order history before you've made a single manual choice. What shipped: Node.js/Express, PostgreSQL, 10 integrated retailers, 200+ brands, Stripe checkout, A/B experimentation, and an admin dashboard.",
    broke: "I built the personalization engine before I had anything to personalize — weeks into recommendation logic before I asked what a new user actually sees. The answer was nothing. The second problem: the product catalog required scraping, which meant code I can't audit running inside a product I was considering shipping.",
    learned: "Design the zero-data state before you design the system that fills it — I got this exactly backwards. The harder lesson: I was evaluating the product by whether it worked, not by whether it was trustworthy. Those are different criteria.",
    nextSteps: "I'd run an explicit vs. implicit onboarding A/B test to validate the cold start hypothesis. I'd also audit every external integration before shipping — not as a checklist, but as a genuine 'do I understand what this code accesses?' review.",
    keyLearning: "The scraping workaround that unlocked the product catalog is also the code I can't audit — getting something built and trusting what was built are not the same problem.",
    artifacts: {
      screenshots: [
        "/projects/muse/welcome.png",
        "/projects/muse/home-feed.png",
        "/projects/muse/chat.png",
      ],
      screenshotCaptions: [
        "Welcome: sign in or browse as guest",
        "Home feed: follow brands like you follow people",
        "Talk with Muse: AI stylist that learns your taste",
      ],
      liveUrl: "https://muse.shopping",
    },
  },
  {
    slug: "llm-explainer",
    title: "LLM Explainer",
    oneLiner: "An interactive LLM learning tool built from Stanford CME 295 lectures — building it forced me to understand each concept, not just consume it.",
    tileInsight: "Building the explainer was the test. You can't fake your way through teaching a concept you don't understand.",
    tags: ["AI", "Research", "Vibecoding"],
    thumbnailColor: "#8B9FBF",
    problem: "I enrolled in Stanford's CME 295 (LLMs for PMs and Executives) to learn how LLMs actually work — not at a surface level, but well enough to make good product decisions about them. Reading the slides and watching lectures wasn't clicking fast enough. I needed something I could interrogate, not just consume.",
    hypothesis: "If I built the learning tool myself — forcing me to explain each concept clearly enough to code it — I'd understand the Stanford material faster than reading it.",
    built: "All content is sourced from Stanford CME 295 — lecture notes, slides, and transcripts — with full attribution in the header.\n\nSix concepts from the course — tokenization, embeddings, transformers, training, RLHF, agents — each with an interactive playground you can actually poke at. Saves to your iPhone home screen as a standalone app. A floating recorder lets you log questions by voice as you go, tagged to whichever concept you're on. One tap sends everything to ChatGPT, Notes, or Messages; download as a text file if you're on desktop.",
    broke: "The share button is built and shipped but not yet verified on a real iPhone — there's no way to test iOS-native share sheets from a laptop. Voice recording may also be unreliable when the app is running in home-screen mode, which is a known iPhone limitation. The one-tap export is the workaround.",
    learned: "Building the explainer forced me to understand each concept well enough to write interactive examples — that's a different level than reading a paper. The question recorder revealed something: the moments I got stuck were the most valuable ones. Logging them turned the stuck moments into a record of where AI education actually breaks down.",
    nextSteps: "Verify the share sheet on a real iPhone. Add more concepts as the CME 295 course progresses. The question archive is already a record of where AI education actually breaks down — a PM's field notes on learning each concept from scratch.",
    keyLearning: "Building the tool forced me to understand each concept well enough to explain it. That's a different test than reading a paper — and a harder one to fake.",
    artifacts: {
      screenshots: [
        "/projects/llm-explainer/playground.gif",
        "/projects/llm-explainer/mobile-hero.png",
        "/projects/llm-explainer/desktop-full.png",
      ],
      screenshotCaptions: [
        "The Text-as-Numbers playground: sentence → tokens → IDs → embeddings in meaning space",
        "Mobile hero — saves to your phone home screen as a standalone app",
        "Full walkthrough: six concepts from Stanford CME 295, each with an interactive playground",
      ],
      liveUrl: "https://schlacter.me/llm-explainer",
    },
  },
  {
    slug: "claude-skills",
    title: "Claude Skills",
    oneLiner: "A concept product for persistent AI instruction sets — tell Claude once, it applies your preferences forever.",
    tileInsight: "Framing is the product. Nobody asks for a 'persistent system prompt manager.' They might ask for a skill.",
    tags: ["AI", "Product Design", "Vibecoding"],
    thumbnailColor: "#F5C5B0",
    problem: "Every Claude conversation starts from scratch. You re-explain your tone, your context, your preferences — session after session. The model is capable; the interface forgets.",
    hypothesis: "If you frame AI customization as 'skills' rather than 'system prompts,' you remove the technical barrier. Most people don't know what a system prompt is. Everyone knows what a skill is.",
    built: "A concept site that shows the product working before asking anyone to sign up. The core bet: lead with a live chat preview demonstrating a skill in action, not a feature list. Two pathways — browse pre-built skills or create your own — sized for two different mental models.",
    broke: "The site shows what persistent skills could feel like — but the actual Claude interface doesn't support this natively. I was designing for a gap in the product, not an existing surface. The thing I shipped is a pitch, not a product.",
    learned: "Building a concept product is different from building a functional one. The constraint isn't 'can I build this' — it's 'can I make someone believe this should exist.' That's mostly a copywriting and sequencing problem.",
    nextSteps: "If Anthropic ships persistent memory or a skills layer, this design is a ready-made reference. The real test would be a working prototype — a Chrome extension that actually persists instructions across sessions would turn a concept into a proof of concept.",
    keyLearning: "Naming matters more than features. 'Claude Skills' communicates the idea in two words. 'Persistent system prompt manager' communicates nothing to anyone who doesn't already know what they want.",
    services: [
      {
        layer: "Design",
        note: "UI/UX concept and information architecture",
        items: ["Landing page layout", "Live demo component", "Use case personas", "CTA hierarchy"],
      },
      {
        layer: "Frontend",
        note: "Static site built with vibecoding",
        items: ["Next.js", "Tailwind CSS", "Vercel deployment"],
      },
    ],
    artifacts: {
      screenshots: [
        "/projects/claude-skills/hero.png",
        "/projects/claude-skills/live-demo.png",
        "/projects/claude-skills/use-cases.png",
      ],
      screenshotCaptions: [
        "Landing: tell Claude once, it remembers forever",
        "How it works: pick a skill, Claude opens, press Enter",
        "Browse the gallery: 9 pre-built skills ready in 30 seconds",
      ],
      liveUrl: "https://skills-roan.vercel.app",
    },
  },
  {
    slug: "kindle-libby",
    title: "Kindle × Libby",
    oneLiner: "Automated library-to-Kindle delivery — books show up on your Kindle when a hold comes in. That's it.",
    tileInsight: "Safety and functionality are separate problems — not the same checklist item.",
    tags: ["Utility", "Automation", "AI"],
    thumbnailColor: "#C5D5E8",
    problem: "Every time a library hold came in, I had to open Amazon, navigate to the right page, click through four steps, and confirm. Five minutes per book — manual and completely unnecessary. I wanted them to just appear on my Kindle.",
    hypothesis: "If you can automate the hold-monitoring and delivery steps, the book should show up with no intervention. I was testing whether I could eliminate the manual loop entirely — not just make it easier, but make it invisible.",
    built: "Deployed to the cloud rather than running locally — because a script you have to run is still friction. The notification and dashboard aren't extra features; they're the only interface, since the automation itself is meant to be imperceptible.",
    broke: "Libby locks the format at borrow time — I was borrowing audiobooks that can't go to Kindle at all, then watching delivery fail silently. Amazon's internal GraphQL API reported zero books in my library even though they existed; I had to switch to browser automation instead. Then I asked about security before connecting my Amazon credentials. Claude started building anyway — what came back was functional code I couldn't audit.",
    learned: "The happy path was maybe 40% of the work — the rest was keeping it running through token expiry, UI changes, and silent failures. When you build something that runs unattended, the design challenge isn't the automation: it's making failures visible in a system designed to be invisible.",
    nextSteps: "I'd build the missing audit layer — a plain-language explanation of what the code accesses and why, generated before first run. That's what I'd want to hand to a non-technical user, and it doesn't exist yet in any AI-assisted build tool.",
    keyLearning: "I asked about the security implications before connecting this to my Amazon account. Claude started building anyway — the security layer had to be explicitly requested, and what came back is still code I can't fully audit.",
    artifacts: {
      screenshots: [
        "/projects/kindle-libby/dashboard-scroll.png",
        "/projects/kindle-libby/libby-loans.png",
      ],
      screenshotCaptions: [
        "The monitoring dashboard — active holds, currently reading, check-for-updates trigger, and a text-based add-books form",
        "The source: Libby showing 14 real library loans the automation watches for Kindle-compatible availability",
      ],
      liveUrl: undefined,
    },
  },
  {
    slug: "home-design",
    title: "Interior Design Tool",
    oneLiner: "A private design tool for my house — gallery, floor plan, designer brief, project roadmap, and an AI advisor that already knows the home.",
    tileInsight: "The hard part of design isn't finding inspiration — it's organizing it into a brief someone else can execute from.",
    tags: ["AI", "Vibecoding", "Consumer"],
    thumbnailColor: "#B85042",
    thumbnailImage: "/projects/home-design/tile-edit.jpg",
    problem: "I bought a house and started collecting design inspiration everywhere at once — Instagram, Amazon, Pinterest, Houzz, Zillow. By the time I sat down with an interior designer, my 'inspiration' lived across six apps with no connective tissue. There was no single place that held what I actually wanted, let alone something I could hand to a contractor.",
    hypothesis: "A private gallery that accepts images from any source can turn scattered screenshots into a coherent brief. Add structure — categories, tags, notes, annotations — and it becomes a shared language between you and your designer. Layer an AI advisor on top that already knows your home, and you can skip re-explaining every time you have a question.",
    built: "A Next.js app with five interconnected sections — all private, behind password-protected access with role-based permissions for different users.\n\nGallery — Images from any source get a category, a like, a note, and optional shape annotations. A tag filter strip and full-text search make it navigable. Layout controls (2–6 columns, aspect ratio) make it browsable.\n\nFloor Plan — An interactive annotated floor plan with pan/zoom, shape annotations per room, and photos linked directly to each annotation. The image-mapping layer that connects inspiration to specific spaces.\n\nDesigner Brief — An editable vision document with color palette, room priorities, must-haves, and a searchable library of 400+ material and texture swatches across 9 categories.\n\nJournal — Rich-text notes with tags, starring, image attachments, and per-note guest sharing via access tokens. The shared language for decisions made with designers and contractors.\n\nPriorities — A 24-month drag-and-drop roadmap with task management: cost estimates, level of effort, owner assignment, vendor tracking, and a visual timeline.\n\nLayered on top: a persistent Claude skill that already knows the home (Spanish Revival, Oakland), the design pillars, and the room priorities. Ask it anything and it has context before you finish the question.",
    broke: "Getting images from Instagram and Amazon is not as simple as a copy-paste — neither platform offers clean APIs for personal use, so the pipeline requires more manual lifting than intended. The AI advisor is also only as good as the brief you give it: writing the skill file took real judgment that couldn't be delegated to the model.",
    learned: "A design gallery is most valuable not as a moodboard but as a translation layer — the goal is turning screenshots into something a contractor can actually act on. The floor plan annotation layer made the biggest difference: once inspiration was mapped to specific rooms, conversations with the designer got more concrete — I stopped saying 'vibes' and started pointing at a map. The AI advisor flipped my assumption: the bottleneck isn't the model's design knowledge, it's getting your taste into a format the model can use.",
    nextSteps: "A browser extension that one-click saves an Amazon product or Instagram screenshot directly to the gallery would unlock the original hypothesis. I'd also extend the skill into a handoff tool: one click to generate a structured brief that can be emailed to a contractor.",
    keyLearning: "Build the brief before you ask the model. The AI advisor only works because I wrote down what I actually wanted — the model holds it, but the taste was mine to define.",
    services: [
      {
        layer: "Gallery",
        note: "Tag filtering, search, shape annotations, layout controls",
        items: [
          "Next.js 15 (App Router)",
          "TypeScript + Tailwind CSS",
          "Vercel Blob (image storage)",
          "Vercel KV / Upstash (metadata)",
          "15+ room categories, multi-column layout picker",
        ],
      },
      {
        layer: "Floor Plan",
        note: "Interactive annotator with linked room photos",
        items: [
          "Pan/zoom with touch pinch support",
          "Shape annotations (rect, circle) per room",
          "Photos linked to each annotation",
          "Current room photo collection",
          "PDF floor plan import",
        ],
      },
      {
        layer: "Designer Brief",
        note: "Editable vision doc + material library",
        items: [
          "Color palette with hex management",
          "Room priorities and must-haves",
          "400+ material/texture swatches (9 categories)",
          "Searchable by keyword and vibe",
          "Must-have image pinning",
        ],
      },
      {
        layer: "Journal",
        note: "Rich-text notes with guest sharing",
        items: [
          "HTML rich text, tags, starring",
          "Image attachments with positioning",
          "Per-note guest access tokens",
          "View-only vs. edit access per guest",
          "Guest contact management",
        ],
      },
      {
        layer: "Priorities",
        note: "24-month drag-and-drop project roadmap",
        items: [
          "Task cost, LOE, owner, vendor fields",
          "Visual 24-month timeline",
          "Drag-and-drop rescheduling",
          "Status tracking (Not Started → Done)",
          "Linked images per task",
        ],
      },
      {
        layer: "AI Design Advisor",
        note: "Persistent Claude skill with full home context",
        items: [
          "Claude Code skill file",
          "Style profile API (KV storage)",
          "Room-by-room knowledge base",
          "Spanish Colonial + MCM sub-skills",
        ],
      },
    ],
    artifacts: {
      screenshots: [
        "/projects/home-design/gallery-tags.png",
        "/projects/home-design/floor-plan.png",
        "/projects/home-design/image-annotation.png",
        "/projects/home-design/journal.png",
        "/projects/home-design/roadmap.png",
        "/projects/home-design/designer-brief.png",
        "/projects/home-design/demo-cb-to-portfolio.gif",
        "/projects/home-design/demo-gallery-interaction.gif",
        "/projects/home-design/shortcut-builder.png",
        "/projects/home-design/instagram-select.png",
        "/projects/home-design/instagram-saved.png",
        "/projects/home-design/amazon-product.png",
        "/projects/home-design/amazon-saved.png",
      ],
      screenshotCaptions: [
        "Gallery: 251 images with tag filter strip, search, and layout controls",
        "Floor plan: annotated rooms with linked photos per space",
        "Image detail: draw annotations, assign category tags, and add notes",
        "Journal: notes with linked inspiration, tags, and guest sharing",
        "Roadmap: 24-month timeline across 61 home improvement projects",
        "Designer brief: vision doc with style direction and room priorities",
        "Crate & Barrel → gallery: one tap saves a product to your private board",
        "Gallery in action: open a tile, add a note, assign a category",
        "The iOS Shortcut that powers the share-sheet pipeline",
        "Selecting a Studio McGee post from Instagram to save",
        "Confirmation: saved to the gallery from Instagram",
        "Amazon product page for a fluted sideboard — one tap to save",
        "Confirmation: saved to the gallery from Amazon",
      ],
      liveUrl: "https://interiordesign.giddins.family",
    },
  },
  {
    slug: "claude-wishlist",
    title: "Claude Wishlist",
    oneLiner: "A living PM listening tool for Claude — a scheduled agent scrapes r/ClaudeAI 4×/week, categorizes what developers are actually asking for, and renders a dashboard with weekly deltas and PM-ranked priorities.",
    tileInsight: "I was going to write my feature wishlist. I built a tool that reads a thousand instead.",
    tags: ["AI", "Product Design", "Research"],
    thumbnailColor: "#F5C5B0",
    problem: "I picked up Claude Code in February and shipped four products in a few months — some days from 11am to 2am, completely unable to stop. I started keeping notes on every gap I hit. But a single consumer's wishlist is one data point. I wanted signal at the scale of the community, not just me.",
    hypothesis: "If I built a listening tool that watched r/ClaudeAI on a cadence, categorized posts into pain points / feature requests / positive / competitor, and ranked what mattered via a PM-style weekly analysis — I'd end up with a better artifact than any static doc I could write. And it would keep updating without me.",
    built: "A scheduled agent (Mon / Wed / Fri / Sun 9am) that scrapes pullpush.io for r/ClaudeAI posts, deduplicates, categorizes with tags (rate_limits, code_quality, context_window, mcp, pricing, ux…), computes week-over-week deltas, and writes raw data + a run summary to a public GitHub repo. The dashboard at /claude-ideas renders three modules: Fresh Findings (latest run, filterable by category), Trends (WoW delta charts), and PM Today (ranked priorities with supporting post IDs). Every stat is clickable — a drilldown drawer fetches the raw posts backing any claim.",
    broke: "The first four weeks of scheduled runs silently 409'd on GitHub's content API because the two file PUTs (posts.json, runs.json) were fired in parallel — the second write's parent commit went stale mid-flight. The dashboard read as 'first run pending' for a month. Fixed by awaiting the first PUT before starting the second.",
    learned: "The model isn't the bottleneck. The interface is. That was my original thesis from 200+ hours of solo building, and the Reddit data backs it — the top tag this run is 'ux', pain points outnumber feature requests 6:3, and the #1 priority that surfaces from PM analysis is agent-autonomy guardrails (not model capability). I also learned that an automated listening tool is harder to keep running than to build — silent failure is the real enemy of a system meant to be invisible.",
    nextSteps: "Add a fourth module: 'Shipped vs. Requested' — compare Reddit feature requests against Anthropic's public changelog so you can see what's been addressed vs. still open. Also: widen the source beyond r/ClaudeAI — HN, Twitter, Discord — to de-bias toward one forum's demographics.",
    keyLearning: "Writing your own feedback is one data point. Building a system that aggregates a thousand other builders' is a product. The Reddit feed tells me where my own experience maps onto the community's — and where I'm an outlier.",
    services: [
      {
        layer: "Scheduled Agent",
        note: "Mon/Wed/Fri/Sun 9am — scrape, categorize, PM-analyze, ingest",
        items: ["Claude agent skill", "pullpush.io (credential-free Reddit)", "6-step prompt pipeline", "PM-style weekly analysis"],
      },
      {
        layer: "Ingest + Storage",
        note: "Public GitHub JSON store with dedup + input validation",
        items: ["POST /api/reddit-pulse/ingest", "GitHub REST API (sequential PUTs)", "Input validation (enums, dates, tag whitelist)", "20% reject threshold"],
      },
      {
        layer: "Dashboard",
        note: "Server-rendered page + lazy drilldown drawer",
        items: ["Next.js App Router", "recharts (trend visuals)", "Lazy /api/reddit-pulse/posts for drilldown", "Every stat clickable → raw source posts"],
      },
      {
        layer: "Health",
        note: "Daily pullpush+GitHub reachability check, email on failure",
        items: ["GET /api/reddit-pulse/health", "Resend email alerts", "Staleness check (>3 days)"],
      },
    ],
    artifacts: {
      screenshots: [
        "/projects/claude-wishlist/dashboard-full.png",
        "/projects/claude-wishlist/drilldown.gif",
        "/projects/claude-wishlist/dashboard.png",
      ],
      screenshotCaptions: [
        "The full dashboard: headline stats, Fresh Findings (filterable by category), Trends, and PM Today — agent-autonomy guardrails ranked top priority",
        "Every stat is clickable — a drilldown drawer opens with the raw Reddit posts backing the number",
        "Earlier view — first successful run: 11 posts, 6 pain points, 3 feature requests, top tag: ux",
      ],
      liveUrl: "https://schlacter.me/claude-ideas",
    },
  },
  {
    slug: "vantara-agent-studio",
    title: "Vantara Agent Studio",
    oneLiner: "A working enterprise agent-builder, built in a day for my Vercel PM application — demo mode included, no API setup required.",
    tileInsight: "Building a prototype for a hiring manager is the same job as building one for a user: show them what's possible, make it real enough to believe.",
    tags: ["AI", "Full-Stack", "Vibecoding"],
    thumbnailColor: "#1A1A1A",
    thumbnailImage: "/projects/vantara-agent-studio/landing.png",
    keyLearning: "The hard design problem in enterprise agent building isn't the AI layer — it's giving non-technical users enough structure to describe what they actually want. The wizard is really a structured prompt for the human, not the model.",
    problem: "The Vercel PM (Agent Platform) role asked for someone who understands where enterprise agent UX is heading. I didn't want to write another cover letter about it. I wanted to build something instead — a real product that shows the PM thinking, not a doc that describes it.",
    hypothesis: "If I can design a credible enterprise agent-building workflow in a day — with real AI responses, a dashboard, and version history — I can show the product judgment that matters for the role without a slide deck.",
    built: "A 4-step wizard that takes an enterprise use case to a deployed agent: collect context, generate Claude-powered clarifying questions, preview agent output, simulate deploy. Built on Vercel AI SDK edge runtime with Upstash Redis for persistence.\n\nThe scenario: a healthcare org managing 500 employees across 15 practices, with three agent types — Leadership (monthly updates), Regulatory (federal policy monitoring), Operations (patient volume). Demo mode lets a hiring manager walk through the full wizard without any API setup. Try it: vantara-agent-studio.vercel.app/build?usecase=comms&demo=true",
    broke: "Demo mode revealed something: the experience with real Claude responses and with pre-baked ones felt almost identical — which means the UX is doing real work independent of the model. The enterprise vertical also taught me that agent use case framing is everything. The same capability reads completely differently depending on the job it's being asked to do.",
    learned: "Structuring the wizard as a 'prompt for the human' — not a configuration UI — was the right call. Non-technical users don't know how to specify what they want from an agent. The clarifying question step isn't about collecting data; it's about helping the user articulate the problem.",
    nextSteps: "This stays a demo unless I get the job. If I kept going: A/B test the clarifying question step — fewer, better questions probably outperform the current model. Version history with semantic diffs (what actually changed about the agent's behavior, not just a timestamp) would be the real product bet.",
    services: [
      {
        layer: "Frontend",
        note: "Next.js 16 App Router with Tailwind CSS 4 and Geist font",
        items: ["Next.js 16.2.2", "TypeScript", "Tailwind CSS 4", "Geist"],
      },
      {
        layer: "AI Layer",
        note: "Vercel AI SDK on Edge Runtime, Claude for questions + preview",
        items: ["Vercel AI SDK", "Anthropic Claude", "Edge Runtime", "Demo mode"],
      },
      {
        layer: "Data & Platform",
        note: "Upstash Redis for agent persistence, Vercel Analytics + Speed Insights",
        items: ["Upstash Redis", "Vercel Analytics", "Vercel Speed Insights"],
      },
    ],
    artifacts: {
      screenshots: [
        "/projects/vantara-agent-studio/landing.png",
        "/projects/vantara-agent-studio/wizard-flow.gif",
        "/projects/vantara-agent-studio/dashboard.png",
      ],
      screenshotCaptions: [
        "Landing: build agents your team can use — no engineering required",
        "The 4-step wizard end-to-end: starting point → clarifying questions → preview → deployed",
        "Dashboard: 3 agents deployed, version history, schedule, and status",
      ],
      liveUrl: "https://vantara-agent-studio.vercel.app",
    },
  },
  {
    slug: "tinker-flywheel",
    title: "Tinker Flywheel",
    oneLiner: "A research memo for Thinking Machines Lab — 2,000+ public developer signals on fine-tuning pain, surfacing the gap between a training tool and a training platform.",
    tileInsight: "Train is solved. Evaluate is where developers get stuck. Iterate is the room they haven't walked into yet.",
    tags: ["AI", "Research", "Product Design"],
    thumbnailColor: "#FAFAFA",
    problem: "Thinking Machines Lab shipped Tinker as a fine-tuning API. I wanted to understand what happens after a developer runs it — what stops them from coming back for a second run, a third, a tenth. If Tinker wants to be a platform and not a one-off tool, the answer matters.",
    hypothesis: "Public developer conversation is a better signal for this than interviews. If I pulled 18 months of signal across Reddit, Hacker News, GitHub, Stack Overflow, and similar sources — then mapped the friction to phases of the fine-tuning lifecycle — the pattern would tell me where Tinker's roadmap gap is.",
    built: "A research memo at schlacter.me/tinker-flywheel backed by a live data pipeline: 2,000+ deduplicated public signals tagged to themes and three lifecycle phases (Train → Evaluate → Iterate). The memo opens with the headline — most post-fine-tuning pain is evaluation: did it get better, is the data clean, did anything break. Iteration questions barely register because developers can't see past the first checkpoint. An interactive theme drill lets readers click into each theme and see the raw source posts.",
    broke: "Reddit skews toward people who wanted to say something, usually strongly. This is a signal-finding exercise, not a population estimate. The memo says so explicitly — but the caveat is easy to miss, and a PM reading quickly could over-index on loudness. The bigger limitation: I don't have access to Tinker's actual support logs, so this is a public mirror of what the real signal probably looks like.",
    learned: "Every theme in the data ladders back to one question. A fine-tuning API that also answers 'did it get better?' closes the loop developers can't close today — and loops compound. Writing the memo forced a sharp product claim I didn't have going in: the gap between a training tool and a training platform is evaluation.",
    nextSteps: "If I kept going: wire the pipeline to refresh weekly so the memo updates as the conversation evolves. Add a second corpus (Tinker's Discord, HF Forum threads on their org page) to triangulate with platform-specific signal. And write a shorter companion memo on the 23% — the iteration themes developers feel but haven't named yet.",
    keyLearning: "A research memo grounded in 2,000+ public signals reads differently than one built on 20 interviews. The raw volume lets you make claims about distribution — not just existence — and that's what a PM roadmap decision actually needs.",
    artifacts: {
      screenshots: [
        "/projects/tinker-flywheel/hero.png",
        "/projects/tinker-flywheel/middle.png",
        "/projects/tinker-flywheel/bottom.png",
      ],
      screenshotCaptions: [
        "The finding: 77% of post-fine-tuning pain is about one run — evaluation, data quality, catastrophic forgetting.",
        "Theme drill: click any theme to see the raw source posts backing the claim.",
        "The so-what: the gap between a training tool and a training platform is evaluation.",
      ],
      liveUrl: "https://schlacter.me/tinker-flywheel",
    },
  },
  {
    slug: "workspace-ai-gaps",
    title: "Gemini Workspace AI Opportunity Map",
    oneLiner: "A PM opportunity map for Google Workspace's AI surface — public user feedback across Reddit, HN, Stack Overflow, App Store, and YouTube, analyzed for theme and competitor mentions.",
    tileInsight: "People don't compare Gemini to Gemini. They compare it to ChatGPT, Copilot, and Notion — and say so publicly.",
    tags: ["AI", "Research", "Product Design"],
    thumbnailColor: "#4285F4",
    problem: "Google ships Gemini across every Workspace surface — Gmail, Docs, Sheets, Meet — but the public conversation about whether it's working is scattered across forums Google doesn't own. I wanted to build the opportunity map a PM on Workspace AI would actually use on Monday morning: what are users saying, where do they say it, and what do they wish it did that ChatGPT already does.",
    hypothesis: "If I pulled curated public feedback across Reddit, Hacker News, Stack Overflow, the App Store, and YouTube, then tagged each post to a theme (accuracy, grounding, memory, tone, integration) and flagged competitor mentions, I'd end up with a dashboard that shows where Gemini loses — and to whom — in the users' own words.",
    built: "A dashboard at schlacter.me/workspace-ai-gaps with three modules: theme distribution (which frictions dominate), competitor callouts (ChatGPT, Copilot, Notion AI — with the specific reasons users prefer each), and a raw-feedback viewer where every stat drills into the source posts. A methodology page documents sourcing, dedup, and theme mapping.",
    broke: "Competitor mentions are directional, not quantitative — Reddit/HN audiences skew technical and early-adopter, so ChatGPT and Copilot over-index. A real version of this analysis would need Workspace's internal CSAT and support ticket data alongside the public signal. The dashboard is honest about this; I'd rather be explicit than let a reader assume representativeness.",
    learned: "The competitor reasons matter more than the counts. 'ChatGPT is more reliable on grounding' and 'Copilot has unified memory across M365' are specific enough to act on — they name a product gap, not just a sentiment. Those quotes are where a Workspace PM could start a roadmap conversation.",
    nextSteps: "Refresh the corpus weekly via scheduled scrape. Add a fourth module — 'Shipped vs. Requested' — comparing the public feedback themes against Google's Workspace AI release notes to see what's been addressed. Also widen to include Twitter/X and LinkedIn signal for enterprise-buyer perspective.",
    keyLearning: "Public user feedback is a starting point for a PM opportunity map, not an endpoint. The work is in pairing this with internal data the team already owns — the two together tell a story neither can alone.",
    artifacts: {
      screenshots: [
        "/projects/workspace-ai-gaps/hero.png",
        "/projects/workspace-ai-gaps/middle.png",
        "/projects/workspace-ai-gaps/bottom.png",
      ],
      screenshotCaptions: [
        "Dashboard hero: theme distribution across 5 public sources.",
        "Competitor callouts: ChatGPT, Copilot, Notion AI — with the specific reasons users prefer each.",
        "Raw feedback viewer: every stat drills into the source posts.",
      ],
      liveUrl: "https://schlacter.me/workspace-ai-gaps",
    },
  },
  {
    slug: "gmail-search-ai",
    title: "Gmail Search AI Research",
    oneLiner: "A PM research artifact on Gmail's AI features — three product hypotheses (Accuracy, Action Gap, Voice) tested against public Reddit feedback.",
    tileInsight: "Pick your product hypotheses first, then let the data tell you which one is real.",
    tags: ["AI", "Research", "Product Design"],
    thumbnailColor: "#EA4335",
    problem: "Gmail ships Gemini AI features — summaries, smart replies, search — but a PM on the team has to pick which bets get the next sprint. Is the biggest lever summary accuracy? Is it closing the gap between reading an email and doing something about it? Or is it making AI drafts sound like the person sending them? Each answer points to a different roadmap.",
    hypothesis: "If I pulled Reddit feedback on Gmail's AI features and categorized each post by three working hypotheses — accuracy (is the summary right?), action-gap (can I do something with it?), and voice (does it sound like me?) — the distribution would point to where the product has headroom.",
    built: "A research dashboard at schlacter.me/gmail-search-ai with three hypothesis tracks: Accuracy, Action Gap, and Voice. Each hypothesis has its own tagline, frequency count, competitor signal, and a set of real Reddit quotes backing it. A methodology page documents how posts were sourced and classified.",
    broke: "Keyword-based classification is a blunt tool — I had to re-read borderline posts to decide which hypothesis they really belonged to. The corpus also skews toward users who had a problem; a real PM signal would need to pair this with Gmail's internal usage data to know which hypothesis maps to the biggest user segment.",
    learned: "Picking your hypotheses before you tag the posts is the right sequencing. It makes you commit to a product theory, then test whether the data actually fills those bins. If one hypothesis pulls 5% of signal, that's as useful as one pulling 50% — the distribution is the insight.",
    nextSteps: "Deepen the competitor comparison (Superhuman, Copilot, Notion AI) — each has a distinctive take on one of the three hypotheses. Add a fourth hypothesis if the data suggests one the original three miss. Build a sketch prototype for whichever hypothesis has the biggest headroom.",
    keyLearning: "A PM's most valuable move isn't enumerating every complaint about a feature. It's picking a handful of testable product hypotheses, then reading the data through those lenses — and being willing to say the losing hypothesis was wrong.",
    artifacts: {
      screenshots: [
        "/projects/gmail-search-ai/hero.png",
        "/projects/gmail-search-ai/middle.png",
        "/projects/gmail-search-ai/bottom.png",
      ],
      screenshotCaptions: [
        "Dashboard hero: three working hypotheses — Accuracy, Action Gap, Voice.",
        "Each hypothesis has a tagline, frequency count, and the real Reddit quotes backing it.",
        "Competitor signal per hypothesis — what Superhuman, Copilot, Notion AI do differently.",
      ],
      liveUrl: "https://schlacter.me/gmail-search-ai",
    },
  },
  {
    slug: "acc-omni-customer-pulse",
    title: "ACC Omni Customer Pulse",
    oneLiner: "A research memo for Walmart's Auto Care Centers PM role — the end-to-end customer journey read from public Reddit voices, with friction mapped to every stage.",
    tileInsight: "Costco doesn't win on price or speed. It wins on a single predictable promise kept every time — reproducibly.",
    tags: ["Research", "Product Design"],
    thumbnailColor: "#0071CE",
    problem: "Walmart's Auto Care Centers are quietly one of the largest tire-and-oil retailers in the US, but the end-to-end customer experience isn't visible from the outside. A PM applying for the ACC Omni role needs to show they understand where the journey actually leaks — not guess.",
    hypothesis: "If I mapped 18 months of public Reddit comments about Walmart ACC and Sam's Club against the six stages of the omni journey (Discover → Schedule → Check-in → Service → Pickup → Post-visit), and included a Costco / Discount Tire benchmark set, the friction pattern would show itself.",
    built: "A research memo at schlacter.me/acc-omni-customer-pulse with four layers: a stats bar (every number drills into source posts), a launches-vs-signal timeline (Walmart has been shipping against this — 10 of 2,582 stores is 0.4%), a journey view with friction ranked by stage, and a set of experiments the signal suggests. Every quote links to its Reddit source. Methodology page documents the full pipeline.",
    broke: "Reddit skews toward users who wanted to say something, usually strongly. I was explicit: this is signal-finding, not a population estimate of satisfaction. The real version would triangulate with ConsumerAffairs, store reviews, and app store reviews. I also couldn't validate against Walmart's internal CSAT — but I said so in the memo.",
    learned: "Friction concentrates at Check-in and Service — where the digital promise (an appointment was booked, a service was paid for) doesn't survive the handoff to the store. A 7am appointment becomes a 9am start. An in-app work order gets eaten mid-inspection. Customers name the price they paid for saving money: their time, unpredictably.",
    nextSteps: "Layer in internal CSAT and store-review data. Run a store-level variance analysis — which locations already ship the ACC of the Future blueprint well, and what's different about their ops? Prototype one of the experiments: an in-app check-in confirmation that keeps the digital promise through the store handoff.",
    keyLearning: "Building a PM artifact for a specific role means doing the work the team does — not describing it. Twenty hours of real customer-voice analysis is a better cover letter than any doc.",
    artifacts: {
      screenshots: [
        "/projects/acc-omni-customer-pulse/hero.png",
        "/projects/acc-omni-customer-pulse/middle.png",
        "/projects/acc-omni-customer-pulse/bottom.png",
      ],
      screenshotCaptions: [
        "Research memo hero: where the end-to-end ACC experience leaks, from public customer voice.",
        "Launches vs. signal — Walmart has been shipping the right blueprint; it's the scale that's lagging.",
        "Journey view: friction ranked by stage, every quote links to Reddit source.",
      ],
      liveUrl: "https://schlacter.me/acc-omni-customer-pulse",
    },
  },
  {
    slug: "cohere-developer-experience",
    title: "Cohere Developer Experience",
    oneLiner: "A PM analysis for Cohere — where the developer surface undersells Cohere's real enterprise wedge, with public feedback across vendors and themes.",
    tileInsight: "Cohere's wedge is enterprise deployment. The playground doesn't say so.",
    tags: ["AI", "Research", "Product Design"],
    thumbnailColor: "#FF6B35",
    problem: "Cohere has a real wedge in enterprise deployment — data residency, VPC, multi-cloud — but developers discovering Cohere through the playground, SDK quickstart, or model selection flow don't see that wedge. Those surfaces still treat Cohere like a generic LLM vendor. The enterprise buyer converts because of residency; the enterprise user converts because of DX. Both have to work.",
    hypothesis: "If I analyzed developer feedback across Cohere, OpenAI, and Anthropic — mapped to themes (docs, SDK, playground, error surfacing, model selection) — the DX gap would show itself, and I could recommend where to close it first.",
    built: "A dashboard at schlacter.me/cohere-developer-experience with vendor-by-vendor theme breakdowns across Cohere, OpenAI, and Anthropic. A top-level thesis anchors the analysis: close the DX gap between Cohere's enterprise wedge and its developer surfaces. Every theme drills into source posts.",
    broke: "The vendor comparison is small-N on Cohere (they have a smaller developer community than OpenAI or Anthropic), which means the themes surface but the proportional claims are fragile. I flagged this in the analysis. The real version would pair this with Cohere's internal Discord and support ticket data.",
    learned: "The gap between an enterprise buyer's wedge and a developer's first-run experience is a PM problem, not a marketing problem. Enterprise residency is the reason a buyer picks Cohere — but the developer logs in and sees 'another LLM playground.' Nothing communicates the wedge at the moment it matters.",
    nextSteps: "Build a mockup of a Cohere playground that leads with the enterprise wedge — 'pick your deployment region,' 'choose VPC or SaaS,' 'residency on by default.' Test whether enterprise buyers convert to enterprise users faster when the DX reflects the wedge.",
    keyLearning: "A company's positioning and its developer surface are the same product problem. Close the gap, and the wedge compounds. Leave it open, and the wedge stays in the sales deck.",
    artifacts: {
      screenshots: [
        "/projects/cohere-developer-experience/hero.png",
        "/projects/cohere-developer-experience/middle.png",
        "/projects/cohere-developer-experience/bottom.png",
      ],
      screenshotCaptions: [
        "Dashboard hero: Cohere's enterprise wedge vs. its developer surface.",
        "Vendor-by-vendor theme breakdown — Cohere, OpenAI, Anthropic.",
        "Every theme drills into source posts.",
      ],
      liveUrl: "https://schlacter.me/cohere-developer-experience",
    },
  },
  {
    slug: "managed-agents-pulse",
    title: "Managed Agents Pulse",
    oneLiner: "A live developer-conversation tracker for Anthropic's Managed Agents API — scheduled scrape, categorization, and dashboard showing what early adopters are actually asking for.",
    tileInsight: "A new API's early public signal is a PM's best free research — if you're there from day one.",
    tags: ["AI", "Research", "Automation"],
    thumbnailColor: "#0F0F13",
    problem: "Anthropic shipped the Managed Agents API on April 10, 2026. I wanted a live read of what developers were saying about it — not a one-shot survey, but a standing feed a PM could open every morning and see what shifted overnight.",
    hypothesis: "If I built a scheduled agent that watched public developer forums for Managed Agents posts, categorized them into four buckets (Momentum, Friction, Use Case, Feature Request), and rendered the result as a dashboard, I'd have a PM listening tool that got sharper every week the API was live.",
    built: "A dark-mode dashboard at schlacter.me/managed-agents-pulse backed by a scheduled agent that scrapes public forums, categorizes posts, and writes run summaries to a public GitHub repo (hbschlac/build-log). The dashboard pulls the latest runs, shows headline stats, and renders category breakdowns. Every post is linked to its source.",
    broke: "The API launched April 10, 2026 — the corpus was thin for the first few weeks, and the dashboard said so: 'Collecting data — check back as the conversation builds.' Early-adopter signal is loud but unrepresentative; I was explicit that this is directional, not a verdict.",
    learned: "A live listening tool beats a static memo for anything evolving. The cost is maintenance — scheduled jobs fail silently if you're not watching. The win is compounding signal: by week four, you have month-over-month deltas no survey can produce.",
    nextSteps: "Widen the sources beyond Reddit/HN — Discord, X, Anthropic's forum itself. Add a 'Shipped vs. Requested' module comparing developer asks against Anthropic's API changelog. Alert if a new post matches a high-priority theme (e.g., rate limits, pricing) within 10 minutes of being posted.",
    keyLearning: "The window after a new API ships is the most honest public signal you'll get. Developers haven't built up workarounds yet — so what they ask for is what's actually missing.",
    artifacts: {
      screenshots: [
        "/projects/managed-agents-pulse/hero.png",
        "/projects/managed-agents-pulse/middle.png",
        "/projects/managed-agents-pulse/bottom.png",
      ],
      screenshotCaptions: [
        "Dark-mode dashboard: live developer pulse on Anthropic's Managed Agents API.",
        "Category breakdowns — Momentum, Friction, Use Case, Feature Request.",
        "Every post links to its source forum.",
      ],
      liveUrl: "https://schlacter.me/managed-agents-pulse",
    },
  },
  {
    slug: "claude-code-insights",
    title: "Claude Code Insights",
    oneLiner: "A live stats page tracking how much I actually ship with Claude Code — hours, sessions, commits, and top projects, updated weekly from local JSONL transcripts.",
    tileInsight: "If you're going to claim you're a power user, the number should be on the page.",
    tags: ["AI", "Automation", "Utility"],
    thumbnailColor: "#1A1A1A",
    problem: "I kept saying 'I use Claude Code a lot' without a number behind it. A PM claim without data is just vibes. I wanted a page I could point to that showed the actual volume — hours, sessions, commits, which projects took how much time — so the claim was checkable.",
    hypothesis: "Claude Code logs every session to JSONL transcripts on my local machine. If I wrote an aggregator that walked the transcripts, rolled them up by month, cross-referenced with my GitHub commit history, and rendered the result as a public page on schlacter.me, the whole thing could update weekly with one command.",
    built: "A public stats page at schlacter.me/claude-code showing headline KPIs (hours, sessions, commits, days active), month-by-month breakdown, and top projects by time. Data comes from a local aggregator.py that parses ~/.claude/projects/ JSONL transcripts + git log. A render_social_image.py script generates a 1200x1200 PNG for LinkedIn. The whole workflow runs from one natural-language prompt to Claude Code — the prompt is copy-pasteable on the page.",
    broke: "Session duration is estimated from timestamps — idle time between tool calls inflates hours. I was explicit about the methodology. The public GitHub commit count misses private repos, which is most of my work; I linked the GitHub profile so readers can see for themselves.",
    learned: "Making your own usage data public changes how you use the product. Once the number is on a page, you notice when it drops. The page isn't just a portfolio artifact — it's a feedback loop on my own habits.",
    nextSteps: "Automate the weekly refresh via scheduled task instead of manual prompt. Add a private/public commit split so the count is less misleading. Chart the hours-per-week trend as a sparkline at the top — the shape tells the story better than a table.",
    keyLearning: "A PM claim about yourself is just another product claim. The honest version is the one with the data behind it — and the willingness to update the number when it's embarrassing.",
    artifacts: {
      screenshots: [
        "/projects/claude-code/hero.png",
        "/projects/claude-code/middle.png",
        "/projects/claude-code/bottom.png",
      ],
      screenshotCaptions: [
        "Stats page hero: hours, sessions, commits, days active — updated weekly.",
        "Month-by-month breakdown with top projects per month.",
        "The copy-pasteable prompt that regenerates the whole thing.",
      ],
      liveUrl: "https://schlacter.me/claude-code",
    },
  },
  {
    slug: "linkedin-feed",
    title: "LinkedIn Newsfeed Agent",
    oneLiner: "A product concept and interactive case study for LinkedIn's Senior PM (Feed) role — a Newsfeed Agent that activates on Save and turns passive engagement into completed professional actions.",
    tileInsight: "Any platform can build a bookmark. Only LinkedIn can build one that acts.",
    tags: ["AI", "Product Design", "Vibecoding"],
    thumbnailColor: "#0A66C2",
    problem: "LinkedIn's feed drives massive engagement — comments +37% YoY, video watch time +36% YoY — but most of that intent evaporates. Save is the one signal that captures real professional intent, and it sits idle. You save a job post, a thought leader, an article, and nothing happens next.",
    hypothesis: "If I could pitch the Senior PM (Feed) role with a real product concept instead of a cover letter describing one, the case study itself would show the PM thinking. The bet: a scrollable, interactive web app grounded in LinkedIn's own earnings data is more persuasive than any doc.",
    built: "A scrollable case study at linkedin-feed.schlacter.me framed around one product concept — a Newsfeed Agent that activates on Save. The page opens with LinkedIn's real momentum metrics (pulled from Q2/Q3 FY25 earnings), then builds the argument for why Save is the strongest intent signal and what an agent layer on top of it unlocks.\n\nThe interactive prototype lets you pick a scenario — Job opportunity, Someone to reach out to, Article to act on — and see the agent draft the completed action in context: 'Apply for me,' 'Draft the outreach,' 'Summarize and ask what you want to do with it.' The Premium upsell is designed-in: agent actions are gated above the free tier, extending the $2B+ Premium flywheel.",
    broke: "The hardest part wasn't the prototype — it was writing the case study without sounding like an outsider telling LinkedIn what to build. I rewrote the framing three times to land on opportunity-only language grounded in LinkedIn's own earnings. The demo surface is a mockup, not a working agent: I'm simulating the intent-capture flow, not running a real model on real saves.",
    learned: "A product concept grounded in a company's own public data reads differently than one built on outside assumptions. Anchoring to LinkedIn's earnings numbers (+37% comments, $2B+ Premium run rate) did more work than any framework I could invent. The other lesson: for a feed product, the demo has to feel like the feed — a deck or doc couldn't carry this.",
    nextSteps: "If I get the interview, build a second scenario — the Silent Sleuther mode, where the agent surfaces career signals without requiring a visible engagement. Also add a measurement section: save-to-action conversion rate as the new leading indicator, with a napkin model of what moving it from ~0% to 20% would unlock for Premium and Jobs revenue.",
    keyLearning: "Building a product concept for a hiring manager is the same job as building one for a user: show them what's possible, make it real enough to believe, ground every claim in data they already trust.",
    artifacts: {
      screenshots: [
        "/projects/linkedin-feed/hero.png",
        "/projects/linkedin-feed/opportunities.png",
        "/projects/linkedin-feed/demo.png",
      ],
      screenshotCaptions: [
        "The thesis: LinkedIn's feed drives massive engagement — AI can make every interaction count. Earnings data from Q2/Q3 FY25.",
        "The save signal: real Reddit quotes showing members treating Save as an intent signal LinkedIn hasn't yet acted on.",
        "The prototype: pick a scenario — Job opportunity, Someone to reach out to, Article to act on — and the Newsfeed Agent drafts the completed action.",
      ],
      liveUrl: "https://linkedin-feed.schlacter.me",
    },
  },
  {
    slug: "ldor",
    title: "L'dor",
    oneLiner: "A modern Judaica brand built for the next generation.",
    tileInsight: "Validating that something looks right is not the same as validating that people will pay for it.",
    tags: ["E-commerce", "Brand", "AI"],
    thumbnailColor: "#D4C8E8",
    problem: "I'm that 28-year-old — moving into my first real apartment, wanting to host Shabbat, and realizing that modern Judaica basically doesn't exist. Everything available was either synagogue gift shop or family heirloom: dated, overpriced for institutions, or designed for someone else entirely.",
    hypothesis: "I surveyed over 100 young Jewish adults before building anything. Same answer every time: feel like CB2, not a synagogue gift shop — and priced for someone buying it themselves at 27, not receiving it as a wedding gift.",
    built: "A brand and a six-product collection — everything on a Shabbat table — with pricing anchored at $22 (something you'd buy yourself) and $88 (something you'd give as a gift). The marketing site came first, deliberately: if the aesthetic didn't resonate, the infrastructure wouldn't have mattered.",
    broke: "The site looks like a real store — the buttons don't go anywhere. I proved aesthetic fit; purchase intent is still an open question. The harder constraint: deciding on the palette, product lineup, and brand voice required actual judgment the model couldn't supply.",
    learned: "Sequencing brand before infrastructure was right: if the aesthetic doesn't work, the checkout button doesn't matter. But the harder constraint in brand work isn't what the model can produce — it's what you can decide.",
    nextSteps: "The brand is validated. The business model isn't. A waitlist with a $10 deposit would tell me more than any survey — if 50 people put down money before the product ships, the business case is real.",
    keyLearning: "You can describe a feeling to a model — modern but rooted, accessible but considered. Translating that into actual design decisions is the work that can't be delegated.",
    artifacts: {
      screenshots: [
        "/projects/ldor/hero.png",
        "/projects/ldor/site-collection.png",
        "/projects/ldor/site-product.png",
        "/projects/ldor/site-bundle.png",
      ],
      screenshotCaptions: [
        "Landing: Judaica, reimagined for you — pricing anchored at $22 and $88",
        "The collection: six pieces for the Shabbat table — Every Holiday. Every Shabbat.",
        "Shabbat Candleholder Set PDP — $48 anchor product, warm editorial photography",
        "Starter Bundle: $88 gift-mode entry with three of the most-requested pieces",
      ],
      liveUrl: undefined,
    },
  },
];
